### ISSUE TITLE
Mandrill API response 500: No such template

### ISSUE THREAD

**Issue by alzearafat** [artemrizhov/django-mail-templated#18] opened 2016-02-17 07:20 UTC
Hi,

I'm having difficulties using django-mail-templated. When I tried to send email through form, I get this error : 

(I'm pretty sure the template is exsist in there. I'm using Djrill plugin and Django 1.9)

```
MandrillAPIError at /order/

Sending a message to Frect1974@dayrep.com from alzea.arafat@gmail.com
Mandrill API response 500:
{
  "status": "error", 
  "message": "No such template \"email/order_email.html\"", 
  "code": 5, 
  "name": "Unknown_Template"
}
```

This is my views.py

```
from mail_templated import send_mail

@login_required
def order_form(request):
    if request.method == "POST":
        form = OrderForm(request.POST, request.FILES)
        if form.is_valid():
            order = form.save(commit=False)
            order.tanggal_order = datetime.datetime.now()
            order.save()
            from_email = 'alzea.arafat@gmail.com'
            send_mail('email/order_email.html', {'order': order}, from_email, [order.email])
            return render(request, 'order_app/order_success.html')
    else:
        form = OrderForm()
    return render(request, 'order_app/order_form.html', {'form': form})
```

My order_email.html template:

```
{% extends "email/base.html" %}

{% block subject %}
Hello {{ order.nama }}
{% endblock %}

{% block html %}
This is an <strong>{{ order.id }}</strong> message.
{% endblock %}
```

My app directory tree :

![alt text](http://i65.tinypic.com/2hwnsde.png "Logo Title Text 1")

Thank you in advance for any help you can provide :)

Regards,

**Comment by artemrizhov** [comment] 2016-02-17 13:33
Hi! Thanks for contacting me with this problem. Could you please provide the call stack?

**Comment by artemrizhov** [comment] 2016-02-17 13:44
@alzearafat Hi! Thanks for contacting me with this problem. Could you please provide the call stack?

**Comment by artemrizhov** [comment] 2016-02-17 14:17
Actually, it seems there is no problem with finding your email template by mail_templated app. The error is probably going from Mandrill. I think the problem is caused by the `template_name` property set on the message object. This is from Djrill documentation:
> If template_name is set, Djrill will use Mandrill’s messages/send-template API, and will ignore any body text set on the EmailMessage.

As a workaround you can unset the `template_name` property before sending the message. Could you please try this instead of `send_mail`:
```
from mail_templated import EmailMessage
message = EmailMessage(
    'email/hello.tpl', {'user': user}, from_email, [user.email], render=True)
del message.template_name
message.send()
```
If this works, I'll implement more compact method for such cases.

Thanks in advance :)

**Comment by artemrizhov** [comment] 2016-02-17 16:43
@alzearafat 
I've added cleanup of the message object. Please try this version
```console
pip install -U git+https://github.com/artemrizhov/django-mail-templated.git@feature/cleanup
```

**Comment by artemrizhov** [comment] 2016-02-19 16:27
@alzearafat 
Merged the change into the master branch. It should work just out of the box with the `send_mail()` function. I close this Issue for now, please let me know if there is still any problem.

**Closed by artemrizhov** 2016-02-19 16:27 UTC

**Comment by artemrizhov** [comment] 2016-02-19 16:30
@taxido This also should fix your problem.

**Comment by alzearafat** [comment] 2016-02-25 04:01
Hi @artemrizhov 

Sorry for late response,

Thank you for quick fix for this issue, really helped me alot! :D 

I'll mark this issue as closed,

Thanks again :)

Regards,

**Comment by artemrizhov** [comment] 2016-02-25 09:33
I'm glad to know this works for you! Thanks :)
