### ISSUE TITLE
Can't send html, only plain works.

### ISSUE THREAD

**Issue by lomholdt** [artemrizhov/django-mail-templated#27] opened 2016-05-24 10:36 UTC
It seems when i load a template with only `{% block html %}<strong>Text</strong>{% endblock %}` mail is sent as a text/plain message. Anyone having this issue?

Full template looks like this
```
{% extends 'mail_templated/base.tpl' %}

{% block subject %}
Din bruger på Klinikker.dk
{% endblock %}

{% block html %}
    <h1>Hello there</h1>
{% endblock %}
```

**Comment by lomholdt** [comment] 2016-05-24 10:48
It seems to work if I define a body as well.

**Comment by artemrizhov** [comment] 2016-05-25 00:55
Hi! Could you please run tests?

**Comment by artemrizhov** [comment] 2016-08-19 23:58
@lomholdt Could you please run tests?

**Comment by artemrizhov** [comment] 2016-10-20 11:03
Closing this issue because I can't reproduce this problem.

**Closed by artemrizhov** 2016-10-20 11:03 UTC
